GET  http://localhost:3000/study

###
GET  http://localhost:3000/study?page=1&pageSize=6&order=recent&keyWord=

###
GET  http://localhost:3000/study/adfc1706-a7f6-4c6e-a006-1733a854afbb

###
POST   http://localhost:3000/study
Content-Type: application/json

{
    "nickname": "d489",
    "studyName": "개발 공부하기",
    "background": "356",
    "password": "12345678"
}

###
PATCH   http://localhost:3000/study/b5fce837-421d-44ac-8107-cd14ad8bd2cc
Content-Type: application/json

{
    "nickname": "dggsfs",
    "studyName": "테스트",
    "description": "",
    "point": 10
}

###
DELETE  http://localhost:3000/study/b5fce837-421d-44ac-8107-cd14ad8bd2cc

###
POST http://localhost:3000/study/dd06dc05-6670-4358-bf0b-eef84c2de979/auth
Content-Type: application/json

{
    "password" : "222222fdgdf"
}