GET  http://localhost:3000/study

###
GET  http://localhost:3000/study?page=1&pageSize=6&order=recent&keyWord=

###
GET  https://localhost:3000/study/ede81528-e6be-450c-9f30-ea4a97906300

###
POST   http://localhost:3000/study
Content-Type: application/json

{
    "nickname": "d489",
    "studyName": "개발 공부하기",
    "background": "356",
    "password": "12345678"
}

###
PATCH   http://localhost:3000/study/b5fce837-421d-44ac-8107-cd14ad8bd2cc
Content-Type: application/json

{
    "nickname": "dggsfs",
    "studyName": "테스트",
    "description": "",
    "point": 10
}

###
DELETE  http://localhost:3000/study/b5fce837-421d-44ac-8107-cd14ad8bd2cc

###
POST http://localhost:3000/study/dd06dc05-6670-4358-bf0b-eef84c2de979/auth
Content-Type: application/json

{
    "password" : "222222fdgdf"
}


###

GET https://onest-term-study-forest-be-3team-rovo.onrender.com/study?pageSize=24

###

PATCH   http://onest-term-study-forest-be-3team-rovo.onrender.com/study/51a4bc4c-2bb4-4ed8-8dc1-2efcd041588b
Content-Type: application/json

{
    "nickname": "이유디",
    "studyName": "UX 스터디",
    "description": "Steady And Slow Wins The Race!!",
    "point": 310
}

###

DELETE http://onest-term-study-forest-be-3team-rovo.onrender.com/study/51a4bc4c-2bb4-4ed8-8dc1-2efcd041588b