GET  http://localhost:3000/study

###
GET  http://localhost:3000/study?page=&pageSize=&order=recent&keyWord=스턴트

###
GET  http://localhost:3000/study/afeac530-e924-4253-9666-c247f41725aa/habitData?timeZone=


###
POST   http://localhost:3000/study
Content-Type: application/json

{
    "nickname": "d489",
    "studyName": "개발 공부하기",
    "background": "356",
    "password": "12345678"
}

###
PATCH   http://localhost:3000/study/67d1cf14-9b68-42f2-aa09-abd455d3bcd7
Content-Type: application/json

{
    "nickname": "dggsfs",
    "studyName": "테스트",
    "description": "",
    "point": 10
}

###
DELETE  http://localhost:3000/study/6a6579ef-1e4f-410f-9c96-9c54865e4ddf

###
POST http://localhost:3000/study/648ab555-4ca1-40e5-91dc-6fdf0c793488/auth
Content-Type: application/json

{
    "password" : "222222fdgdf"
}